/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcceptInvitationResponse { 
    groupId?: string;
    groupName?: string | null;
    organizerName?: string | null;
    participantCount?: number;
    budget?: number | null;
    drawCompleted?: boolean;
    joinedAt?: string;
}

