/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BudgetSuggestionsResponse { 
    groupId: string;
    suggestions: Array<number> | null;
    count: number;
    participantCount: number;
    suggestionsReceived: number;
    currentBudget?: number | null;
}

