/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DrawValidationDto } from './draw-validation-dto';
import { UserInfoDto } from './user-info-dto';


export interface CreateExclusionRuleResponse { 
    ruleId?: string;
    groupId?: string;
    user1?: UserInfoDto;
    user2?: UserInfoDto;
    createdAt?: string;
    drawValidation?: DrawValidationDto;
}

