/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDto } from './user-info-dto';


export interface ExclusionRuleDto { 
    ruleId?: string;
    user1?: UserInfoDto;
    user2?: UserInfoDto;
    createdAt?: string;
}

