/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssignmentDto } from './assignment-dto';


export interface ExecuteDrawResponse { 
    groupId?: string;
    budget?: number;
    drawCompleted?: boolean;
    drawCompletedAt?: string;
    participantCount?: number;
    assignmentsCreated?: number;
    myAssignment?: AssignmentDto;
}

