/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DrawValidationDto } from './draw-validation-dto';
import { ParticipantDto } from './participant-dto';
import { AssignmentDto } from './assignment-dto';


export interface GetGroupDetailsResponse { 
    groupId: string;
    name: string | null;
    organizerId: string | null;
    organizerName: string | null;
    isOrganizer: boolean;
    budget?: number | null;
    drawCompleted: boolean;
    drawCompletedAt?: string | null;
    createdAt: string;
    participantCount: number;
    participants?: Array<ParticipantDto> | null;
    exclusionRuleCount?: number | null;
    canDraw?: boolean | null;
    drawValidation?: DrawValidationDto;
    myAssignment?: AssignmentDto;
}

