/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetInvitationDetailsResponse { 
    invitationToken?: string;
    groupId?: string;
    groupName?: string | null;
    organizerName?: string | null;
    participantCount?: number;
    drawCompleted?: boolean;
    isValid?: boolean;
}

