/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecipientDto } from './recipient-dto';


export interface GetMyAssignmentResponse { 
    groupId?: string;
    groupName?: string | null;
    budget?: number;
    drawCompletedAt?: string;
    recipient?: RecipientDto;
}

