/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExclusionRuleDto } from './exclusion-rule-dto';


export interface GetExclusionRulesResponse { 
    groupId?: string;
    exclusionRules?: Array<ExclusionRuleDto> | null;
    totalCount?: number;
}

