/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupDto } from './group-dto';


export interface GetUserGroupsResponse { 
    groups: Array<GroupDto> | null;
    totalCount: number;
}

