/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GiftSuggestionsResponse { 
    groupId?: string;
    recipientFirstName?: string | null;
    budget?: number;
    suggestionsMarkdown?: string | null;
    generatedAt?: string;
    aiModel?: string | null;
}

