/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GroupDto { 
    groupId: string;
    name: string | null;
    organizerId: string | null;
    organizerName: string | null;
    isOrganizer: boolean;
    participantCount: number;
    budget?: number | null;
    drawCompleted: boolean;
    joinedAt: string;
    drawCompletedAt?: string | null;
}

