/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantDto { 
    userId: string | null;
    firstName: string | null;
    lastName: string | null;
    joinedAt: string;
    hasWishlist: boolean;
    isOrganizer: boolean;
}

