/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecipientDto { 
    userId?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    hasWishlist?: boolean;
    wishlistLastModified?: string | null;
}

