/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ValidateDrawResponse { 
    groupId?: string;
    isValid?: boolean;
    canDraw?: boolean;
    participantCount?: number;
    exclusionRuleCount?: number;
    errors?: Array<string> | null;
    warnings?: Array<string> | null;
}

