/**
 * SantaVibe API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponse { 
    userId: string | null;
    email: string | null;
    firstName: string | null;
    lastName: string | null;
    token: string | null;
    expiresAt?: string;
}

